baseURL: "https://fbcmuncie.org/"
languageCode: "en-us"
title: "First Baptist Church Muncie"

languageCode: "en-us"
DefaultContentLanguage: "en"
paginate: 12

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

params:
  facebook: "https://www.facebook.com/firstbaptistmuncie"
  twitter: "https://twitter.com/fbcmuncie"
  youtube: "https://youtube.com/c/fbcmuncieorg"
  sitename: "First Baptist Church Muncie"
  author: "Wade Allen"
  og_image: "/images/facebook-image.png"
publishDir: /home/wadeallen/fbcmuncie_published 
buildFuture: True
summaryLength: 5

taxonomies:
   author: people
   role: roles

permalinks:
  roles: /:slug/
  people: /:slug/
  blog: /blog/:year/:month/:day/:slug/
  video: /video/:year/:month/:day/:slug/


outputs:
  home: [ "RSS", "HTML"]  

outputFormats:
   RSS:
      mediatype: "application/rss"
      baseName: "podcast/fbcmuncie"
